/* 
 * Polyvaccine a Polymorphic exploit detection engine.
 *                                                              
 * Copyright (C) 2009  Luis Campo Giralte 
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 *
 * Written by Luis Campo Giralte <luis.camp0.2009@gmail.com> 2009 
 *
 */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#include "syscallnode.h"

#ifdef __FREEBSD__
/*
This command generates the outuput for the syscalls 
grep define /usr/include/sys/syscall.h | awk '{print $2, $3}' | awk '{if (NF == 2) { name = substr($1,5); number=$2; printf("\t{ .name=\"%s\",\t\t.number=%s,\t.matchs=0 },\n",name,$1);}}'

*/

static struct ST_SyscallNode ST_SyscallTable [] = {
	{ .name="exit",		.number=SYS_exit,	.matchs=0 },
	{ .name="fork",		.number=SYS_fork,	.matchs=0 },
	{ .name="read",		.number=SYS_read,	.matchs=0 },
	{ .name="write",		.number=SYS_write,	.matchs=0 },
	{ .name="open",		.number=SYS_open,	.matchs=0 },
	{ .name="close",		.number=SYS_close,	.matchs=0 },
	{ .name="wait4",		.number=SYS_wait4,	.matchs=0 },
	{ .name="link",		.number=SYS_link,	.matchs=0 },
	{ .name="unlink",		.number=SYS_unlink,	.matchs=0 },
	{ .name="chdir",		.number=SYS_chdir,	.matchs=0 },
	{ .name="fchdir",		.number=SYS_fchdir,	.matchs=0 },
	{ .name="mknod",		.number=SYS_mknod,	.matchs=0 },
	{ .name="chmod",		.number=SYS_chmod,	.matchs=0 },
	{ .name="chown",		.number=SYS_chown,	.matchs=0 },
	{ .name="break",		.number=SYS_break,	.matchs=0 },
	{ .name="freebsd4_getfsstat",		.number=SYS_freebsd4_getfsstat,	.matchs=0 },
	{ .name="getpid",		.number=SYS_getpid,	.matchs=0 },
	{ .name="mount",		.number=SYS_mount,	.matchs=0 },
	{ .name="unmount",		.number=SYS_unmount,	.matchs=0 },
	{ .name="setuid",		.number=SYS_setuid,	.matchs=0 },
	{ .name="getuid",		.number=SYS_getuid,	.matchs=0 },
	{ .name="geteuid",		.number=SYS_geteuid,	.matchs=0 },
	{ .name="ptrace",		.number=SYS_ptrace,	.matchs=0 },
	{ .name="recvmsg",		.number=SYS_recvmsg,	.matchs=0 },
	{ .name="sendmsg",		.number=SYS_sendmsg,	.matchs=0 },
	{ .name="recvfrom",		.number=SYS_recvfrom,	.matchs=0 },
	{ .name="accept",		.number=SYS_accept,	.matchs=0 },
	{ .name="getpeername",		.number=SYS_getpeername,	.matchs=0 },
	{ .name="getsockname",		.number=SYS_getsockname,	.matchs=0 },
	{ .name="access",		.number=SYS_access,	.matchs=0 },
	{ .name="chflags",		.number=SYS_chflags,	.matchs=0 },
	{ .name="fchflags",		.number=SYS_fchflags,	.matchs=0 },
	{ .name="sync",		.number=SYS_sync,	.matchs=0 },
	{ .name="kill",		.number=SYS_kill,	.matchs=0 },
	{ .name="getppid",		.number=SYS_getppid,	.matchs=0 },
	{ .name="dup",		.number=SYS_dup,	.matchs=0 },
	{ .name="pipe",		.number=SYS_pipe,	.matchs=0 },
	{ .name="getegid",		.number=SYS_getegid,	.matchs=0 },
	{ .name="profil",		.number=SYS_profil,	.matchs=0 },
	{ .name="ktrace",		.number=SYS_ktrace,	.matchs=0 },
	{ .name="getgid",		.number=SYS_getgid,	.matchs=0 },
	{ .name="getlogin",		.number=SYS_getlogin,	.matchs=0 },
	{ .name="setlogin",		.number=SYS_setlogin,	.matchs=0 },
	{ .name="acct",		.number=SYS_acct,	.matchs=0 },
	{ .name="sigaltstack",		.number=SYS_sigaltstack,	.matchs=0 },
	{ .name="ioctl",		.number=SYS_ioctl,	.matchs=0 },
	{ .name="reboot",		.number=SYS_reboot,	.matchs=0 },
	{ .name="revoke",		.number=SYS_revoke,	.matchs=0 },
	{ .name="symlink",		.number=SYS_symlink,	.matchs=0 },
	{ .name="readlink",		.number=SYS_readlink,	.matchs=0 },
	{ .name="execve",		.number=SYS_execve,	.matchs=0 },
	{ .name="umask",		.number=SYS_umask,	.matchs=0 },
	{ .name="chroot",		.number=SYS_chroot,	.matchs=0 },
	{ .name="msync",		.number=SYS_msync,	.matchs=0 },
	{ .name="vfork",		.number=SYS_vfork,	.matchs=0 },
	{ .name="sbrk",		.number=SYS_sbrk,	.matchs=0 },
	{ .name="sstk",		.number=SYS_sstk,	.matchs=0 },
	{ .name="vadvise",		.number=SYS_vadvise,	.matchs=0 },
	{ .name="munmap",		.number=SYS_munmap,	.matchs=0 },
	{ .name="mprotect",		.number=SYS_mprotect,	.matchs=0 },
	{ .name="madvise",		.number=SYS_madvise,	.matchs=0 },
	{ .name="mincore",		.number=SYS_mincore,	.matchs=0 },
	{ .name="getgroups",		.number=SYS_getgroups,	.matchs=0 },
	{ .name="setgroups",		.number=SYS_setgroups,	.matchs=0 },
	{ .name="getpgrp",		.number=SYS_getpgrp,	.matchs=0 },
	{ .name="setpgid",		.number=SYS_setpgid,	.matchs=0 },
	{ .name="setitimer",		.number=SYS_setitimer,	.matchs=0 },
	{ .name="swapon",		.number=SYS_swapon,	.matchs=0 },
	{ .name="getitimer",		.number=SYS_getitimer,	.matchs=0 },
	{ .name="getdtablesize",		.number=SYS_getdtablesize,	.matchs=0 },
	{ .name="dup2",		.number=SYS_dup2,	.matchs=0 },
	{ .name="fcntl",		.number=SYS_fcntl,	.matchs=0 },
	{ .name="select",		.number=SYS_select,	.matchs=0 },
	{ .name="fsync",		.number=SYS_fsync,	.matchs=0 },
	{ .name="setpriority",		.number=SYS_setpriority,	.matchs=0 },
	{ .name="socket",		.number=SYS_socket,	.matchs=0 },
	{ .name="connect",		.number=SYS_connect,	.matchs=0 },
	{ .name="getpriority",		.number=SYS_getpriority,	.matchs=0 },
	{ .name="bind",		.number=SYS_bind,	.matchs=0 },
	{ .name="setsockopt",		.number=SYS_setsockopt,	.matchs=0 },
	{ .name="listen",		.number=SYS_listen,	.matchs=0 },
	{ .name="gettimeofday",		.number=SYS_gettimeofday,	.matchs=0 },
	{ .name="getrusage",		.number=SYS_getrusage,	.matchs=0 },
	{ .name="getsockopt",		.number=SYS_getsockopt,	.matchs=0 },
	{ .name="readv",		.number=SYS_readv,	.matchs=0 },
	{ .name="writev",		.number=SYS_writev,	.matchs=0 },
	{ .name="settimeofday",		.number=SYS_settimeofday,	.matchs=0 },
	{ .name="fchown",		.number=SYS_fchown,	.matchs=0 },
	{ .name="fchmod",		.number=SYS_fchmod,	.matchs=0 },
	{ .name="setreuid",		.number=SYS_setreuid,	.matchs=0 },
	{ .name="setregid",		.number=SYS_setregid,	.matchs=0 },
	{ .name="rename",		.number=SYS_rename,	.matchs=0 },
	{ .name="flock",		.number=SYS_flock,	.matchs=0 },
	{ .name="mkfifo",		.number=SYS_mkfifo,	.matchs=0 },
	{ .name="sendto",		.number=SYS_sendto,	.matchs=0 },
	{ .name="shutdown",		.number=SYS_shutdown,	.matchs=0 },
	{ .name="socketpair",		.number=SYS_socketpair,	.matchs=0 },
	{ .name="mkdir",		.number=SYS_mkdir,	.matchs=0 },
	{ .name="rmdir",		.number=SYS_rmdir,	.matchs=0 },
	{ .name="utimes",		.number=SYS_utimes,	.matchs=0 },
	{ .name="adjtime",		.number=SYS_adjtime,	.matchs=0 },
	{ .name="setsid",		.number=SYS_setsid,	.matchs=0 },
	{ .name="quotactl",		.number=SYS_quotactl,	.matchs=0 },
	{ .name="nlm_syscall",		.number=SYS_nlm_syscall,	.matchs=0 },
	{ .name="nfssvc",		.number=SYS_nfssvc,	.matchs=0 },
	{ .name="freebsd4_statfs",		.number=SYS_freebsd4_statfs,	.matchs=0 },
	{ .name="freebsd4_fstatfs",		.number=SYS_freebsd4_fstatfs,	.matchs=0 },
	{ .name="lgetfh",		.number=SYS_lgetfh,	.matchs=0 },
	{ .name="getfh",		.number=SYS_getfh,	.matchs=0 },
	{ .name="freebsd4_getdomainname",		.number=SYS_freebsd4_getdomainname,	.matchs=0 },
	{ .name="freebsd4_setdomainname",		.number=SYS_freebsd4_setdomainname,	.matchs=0 },
	{ .name="freebsd4_uname",		.number=SYS_freebsd4_uname,	.matchs=0 },
	{ .name="sysarch",		.number=SYS_sysarch,	.matchs=0 },
	{ .name="rtprio",		.number=SYS_rtprio,	.matchs=0 },
	{ .name="semsys",		.number=SYS_semsys,	.matchs=0 },
	{ .name="msgsys",		.number=SYS_msgsys,	.matchs=0 },
	{ .name="shmsys",		.number=SYS_shmsys,	.matchs=0 },
	{ .name="freebsd6_pread",		.number=SYS_freebsd6_pread,	.matchs=0 },
	{ .name="freebsd6_pwrite",		.number=SYS_freebsd6_pwrite,	.matchs=0 },
	{ .name="setfib",		.number=SYS_setfib,	.matchs=0 },
	{ .name="ntp_adjtime",		.number=SYS_ntp_adjtime,	.matchs=0 },
	{ .name="setgid",		.number=SYS_setgid,	.matchs=0 },
	{ .name="setegid",		.number=SYS_setegid,	.matchs=0 },
	{ .name="seteuid",		.number=SYS_seteuid,	.matchs=0 },
	{ .name="stat",		.number=SYS_stat,	.matchs=0 },
	{ .name="fstat",		.number=SYS_fstat,	.matchs=0 },
	{ .name="lstat",		.number=SYS_lstat,	.matchs=0 },
	{ .name="pathconf",		.number=SYS_pathconf,	.matchs=0 },
	{ .name="fpathconf",		.number=SYS_fpathconf,	.matchs=0 },
	{ .name="getrlimit",		.number=SYS_getrlimit,	.matchs=0 },
	{ .name="setrlimit",		.number=SYS_setrlimit,	.matchs=0 },
	{ .name="getdirentries",		.number=SYS_getdirentries,	.matchs=0 },
	{ .name="freebsd6_mmap",		.number=SYS_freebsd6_mmap,	.matchs=0 },
	{ .name="__syscall",		.number=SYS___syscall,	.matchs=0 },
	{ .name="freebsd6_lseek",		.number=SYS_freebsd6_lseek,	.matchs=0 },
	{ .name="freebsd6_truncate",		.number=SYS_freebsd6_truncate,	.matchs=0 },
	{ .name="freebsd6_ftruncate",		.number=SYS_freebsd6_ftruncate,	.matchs=0 },
	{ .name="__sysctl",		.number=SYS___sysctl,	.matchs=0 },
	{ .name="mlock",		.number=SYS_mlock,	.matchs=0 },
	{ .name="munlock",		.number=SYS_munlock,	.matchs=0 },
	{ .name="undelete",		.number=SYS_undelete,	.matchs=0 },
	{ .name="futimes",		.number=SYS_futimes,	.matchs=0 },
	{ .name="getpgid",		.number=SYS_getpgid,	.matchs=0 },
	{ .name="poll",		.number=SYS_poll,	.matchs=0 },
	{ .name="freebsd7___semctl",		.number=SYS_freebsd7___semctl,	.matchs=0 },
	{ .name="semget",		.number=SYS_semget,	.matchs=0 },
	{ .name="semop",		.number=SYS_semop,	.matchs=0 },
	{ .name="freebsd7_msgctl",		.number=SYS_freebsd7_msgctl,	.matchs=0 },
	{ .name="msgget",		.number=SYS_msgget,	.matchs=0 },
	{ .name="msgsnd",		.number=SYS_msgsnd,	.matchs=0 },
	{ .name="msgrcv",		.number=SYS_msgrcv,	.matchs=0 },
	{ .name="shmat",		.number=SYS_shmat,	.matchs=0 },
	{ .name="freebsd7_shmctl",		.number=SYS_freebsd7_shmctl,	.matchs=0 },
	{ .name="shmdt",		.number=SYS_shmdt,	.matchs=0 },
	{ .name="shmget",		.number=SYS_shmget,	.matchs=0 },
	{ .name="clock_gettime",		.number=SYS_clock_gettime,	.matchs=0 },
	{ .name="clock_settime",		.number=SYS_clock_settime,	.matchs=0 },
	{ .name="clock_getres",		.number=SYS_clock_getres,	.matchs=0 },
	{ .name="ktimer_create",		.number=SYS_ktimer_create,	.matchs=0 },
	{ .name="ktimer_delete",		.number=SYS_ktimer_delete,	.matchs=0 },
	{ .name="ktimer_settime",		.number=SYS_ktimer_settime,	.matchs=0 },
	{ .name="ktimer_gettime",		.number=SYS_ktimer_gettime,	.matchs=0 },
	{ .name="ktimer_getoverrun",		.number=SYS_ktimer_getoverrun,	.matchs=0 },
	{ .name="nanosleep",		.number=SYS_nanosleep,	.matchs=0 },
	{ .name="ntp_gettime",		.number=SYS_ntp_gettime,	.matchs=0 },
	{ .name="minherit",		.number=SYS_minherit,	.matchs=0 },
	{ .name="rfork",		.number=SYS_rfork,	.matchs=0 },
	{ .name="openbsd_poll",		.number=SYS_openbsd_poll,	.matchs=0 },
	{ .name="issetugid",		.number=SYS_issetugid,	.matchs=0 },
	{ .name="lchown",		.number=SYS_lchown,	.matchs=0 },
	{ .name="aio_read",		.number=SYS_aio_read,	.matchs=0 },
	{ .name="aio_write",		.number=SYS_aio_write,	.matchs=0 },
	{ .name="lio_listio",		.number=SYS_lio_listio,	.matchs=0 },
	{ .name="getdents",		.number=SYS_getdents,	.matchs=0 },
	{ .name="lchmod",		.number=SYS_lchmod,	.matchs=0 },
	{ .name="netbsd_lchown",		.number=SYS_netbsd_lchown,	.matchs=0 },
	{ .name="lutimes",		.number=SYS_lutimes,	.matchs=0 },
	{ .name="netbsd_msync",		.number=SYS_netbsd_msync,	.matchs=0 },
	{ .name="nstat",		.number=SYS_nstat,	.matchs=0 },
	{ .name="nfstat",		.number=SYS_nfstat,	.matchs=0 },
	{ .name="nlstat",		.number=SYS_nlstat,	.matchs=0 },
	{ .name="preadv",		.number=SYS_preadv,	.matchs=0 },
	{ .name="pwritev",		.number=SYS_pwritev,	.matchs=0 },
	{ .name="freebsd4_fhstatfs",		.number=SYS_freebsd4_fhstatfs,	.matchs=0 },
	{ .name="fhopen",		.number=SYS_fhopen,	.matchs=0 },
	{ .name="fhstat",		.number=SYS_fhstat,	.matchs=0 },
	{ .name="modnext",		.number=SYS_modnext,	.matchs=0 },
	{ .name="modstat",		.number=SYS_modstat,	.matchs=0 },
	{ .name="modfnext",		.number=SYS_modfnext,	.matchs=0 },
	{ .name="modfind",		.number=SYS_modfind,	.matchs=0 },
	{ .name="kldload",		.number=SYS_kldload,	.matchs=0 },
	{ .name="kldunload",		.number=SYS_kldunload,	.matchs=0 },
	{ .name="kldfind",		.number=SYS_kldfind,	.matchs=0 },
	{ .name="kldnext",		.number=SYS_kldnext,	.matchs=0 },
	{ .name="kldstat",		.number=SYS_kldstat,	.matchs=0 },
	{ .name="kldfirstmod",		.number=SYS_kldfirstmod,	.matchs=0 },
	{ .name="getsid",		.number=SYS_getsid,	.matchs=0 },
	{ .name="setresuid",		.number=SYS_setresuid,	.matchs=0 },
	{ .name="setresgid",		.number=SYS_setresgid,	.matchs=0 },
	{ .name="aio_return",		.number=SYS_aio_return,	.matchs=0 },
	{ .name="aio_suspend",		.number=SYS_aio_suspend,	.matchs=0 },
	{ .name="aio_cancel",		.number=SYS_aio_cancel,	.matchs=0 },
	{ .name="aio_error",		.number=SYS_aio_error,	.matchs=0 },
	{ .name="oaio_read",		.number=SYS_oaio_read,	.matchs=0 },
	{ .name="oaio_write",		.number=SYS_oaio_write,	.matchs=0 },
	{ .name="olio_listio",		.number=SYS_olio_listio,	.matchs=0 },
	{ .name="yield",		.number=SYS_yield,	.matchs=0 },
	{ .name="mlockall",		.number=SYS_mlockall,	.matchs=0 },
	{ .name="munlockall",		.number=SYS_munlockall,	.matchs=0 },
	{ .name="__getcwd",		.number=SYS___getcwd,	.matchs=0 },
	{ .name="sched_setparam",		.number=SYS_sched_setparam,	.matchs=0 },
	{ .name="sched_getparam",		.number=SYS_sched_getparam,	.matchs=0 },
	{ .name="sched_setscheduler",		.number=SYS_sched_setscheduler,	.matchs=0 },
	{ .name="sched_getscheduler",		.number=SYS_sched_getscheduler,	.matchs=0 },
	{ .name="sched_yield",		.number=SYS_sched_yield,	.matchs=0 },
	{ .name="sched_get_priority_max",		.number=SYS_sched_get_priority_max,	.matchs=0 },
	{ .name="sched_get_priority_min",		.number=SYS_sched_get_priority_min,	.matchs=0 },
	{ .name="sched_rr_get_interval",		.number=SYS_sched_rr_get_interval,	.matchs=0 },
	{ .name="utrace",		.number=SYS_utrace,	.matchs=0 },
	{ .name="freebsd4_sendfile",		.number=SYS_freebsd4_sendfile,	.matchs=0 },
	{ .name="kldsym",		.number=SYS_kldsym,	.matchs=0 },
	{ .name="jail",		.number=SYS_jail,	.matchs=0 },
	{ .name="sigprocmask",		.number=SYS_sigprocmask,	.matchs=0 },
	{ .name="sigsuspend",		.number=SYS_sigsuspend,	.matchs=0 },
	{ .name="freebsd4_sigaction",		.number=SYS_freebsd4_sigaction,	.matchs=0 },
	{ .name="sigpending",		.number=SYS_sigpending,	.matchs=0 },
	{ .name="freebsd4_sigreturn",		.number=SYS_freebsd4_sigreturn,	.matchs=0 },
	{ .name="sigtimedwait",		.number=SYS_sigtimedwait,	.matchs=0 },
	{ .name="sigwaitinfo",		.number=SYS_sigwaitinfo,	.matchs=0 },
	{ .name="__acl_get_file",		.number=SYS___acl_get_file,	.matchs=0 },
	{ .name="__acl_set_file",		.number=SYS___acl_set_file,	.matchs=0 },
	{ .name="__acl_get_fd",		.number=SYS___acl_get_fd,	.matchs=0 },
	{ .name="__acl_set_fd",		.number=SYS___acl_set_fd,	.matchs=0 },
	{ .name="__acl_delete_file",		.number=SYS___acl_delete_file,	.matchs=0 },
	{ .name="__acl_delete_fd",		.number=SYS___acl_delete_fd,	.matchs=0 },
	{ .name="__acl_aclcheck_file",		.number=SYS___acl_aclcheck_file,	.matchs=0 },
	{ .name="__acl_aclcheck_fd",		.number=SYS___acl_aclcheck_fd,	.matchs=0 },
	{ .name="extattrctl",		.number=SYS_extattrctl,	.matchs=0 },
	{ .name="extattr_set_file",		.number=SYS_extattr_set_file,	.matchs=0 },
	{ .name="extattr_get_file",		.number=SYS_extattr_get_file,	.matchs=0 },
	{ .name="extattr_delete_file",		.number=SYS_extattr_delete_file,	.matchs=0 },
	{ .name="aio_waitcomplete",		.number=SYS_aio_waitcomplete,	.matchs=0 },
	{ .name="getresuid",		.number=SYS_getresuid,	.matchs=0 },
	{ .name="getresgid",		.number=SYS_getresgid,	.matchs=0 },
	{ .name="kqueue",		.number=SYS_kqueue,	.matchs=0 },
	{ .name="kevent",		.number=SYS_kevent,	.matchs=0 },
	{ .name="extattr_set_fd",		.number=SYS_extattr_set_fd,	.matchs=0 },
	{ .name="extattr_get_fd",		.number=SYS_extattr_get_fd,	.matchs=0 },
	{ .name="extattr_delete_fd",		.number=SYS_extattr_delete_fd,	.matchs=0 },
	{ .name="__setugid",		.number=SYS___setugid,	.matchs=0 },
	{ .name="eaccess",		.number=SYS_eaccess,	.matchs=0 },
	{ .name="nmount",		.number=SYS_nmount,	.matchs=0 },
	{ .name="__mac_get_proc",		.number=SYS___mac_get_proc,	.matchs=0 },
	{ .name="__mac_set_proc",		.number=SYS___mac_set_proc,	.matchs=0 },
	{ .name="__mac_get_fd",		.number=SYS___mac_get_fd,	.matchs=0 },
	{ .name="__mac_get_file",		.number=SYS___mac_get_file,	.matchs=0 },
	{ .name="__mac_set_fd",		.number=SYS___mac_set_fd,	.matchs=0 },
	{ .name="__mac_set_file",		.number=SYS___mac_set_file,	.matchs=0 },
	{ .name="kenv",		.number=SYS_kenv,	.matchs=0 },
	{ .name="lchflags",		.number=SYS_lchflags,	.matchs=0 },
	{ .name="uuidgen",		.number=SYS_uuidgen,	.matchs=0 },
	{ .name="sendfile",		.number=SYS_sendfile,	.matchs=0 },
	{ .name="mac_syscall",		.number=SYS_mac_syscall,	.matchs=0 },
	{ .name="getfsstat",		.number=SYS_getfsstat,	.matchs=0 },
	{ .name="statfs",		.number=SYS_statfs,	.matchs=0 },
	{ .name="fstatfs",		.number=SYS_fstatfs,	.matchs=0 },
	{ .name="fhstatfs",		.number=SYS_fhstatfs,	.matchs=0 },
	{ .name="ksem_close",		.number=SYS_ksem_close,	.matchs=0 },
	{ .name="ksem_post",		.number=SYS_ksem_post,	.matchs=0 },
	{ .name="ksem_wait",		.number=SYS_ksem_wait,	.matchs=0 },
	{ .name="ksem_trywait",		.number=SYS_ksem_trywait,	.matchs=0 },
	{ .name="ksem_init",		.number=SYS_ksem_init,	.matchs=0 },
	{ .name="ksem_open",		.number=SYS_ksem_open,	.matchs=0 },
	{ .name="ksem_unlink",		.number=SYS_ksem_unlink,	.matchs=0 },
	{ .name="ksem_getvalue",		.number=SYS_ksem_getvalue,	.matchs=0 },
	{ .name="ksem_destroy",		.number=SYS_ksem_destroy,	.matchs=0 },
	{ .name="__mac_get_pid",		.number=SYS___mac_get_pid,	.matchs=0 },
	{ .name="__mac_get_link",		.number=SYS___mac_get_link,	.matchs=0 },
	{ .name="__mac_set_link",		.number=SYS___mac_set_link,	.matchs=0 },
	{ .name="extattr_set_link",		.number=SYS_extattr_set_link,	.matchs=0 },
	{ .name="extattr_get_link",		.number=SYS_extattr_get_link,	.matchs=0 },
	{ .name="extattr_delete_link",		.number=SYS_extattr_delete_link,	.matchs=0 },
	{ .name="__mac_execve",		.number=SYS___mac_execve,	.matchs=0 },
	{ .name="sigaction",		.number=SYS_sigaction,	.matchs=0 },
	{ .name="sigreturn",		.number=SYS_sigreturn,	.matchs=0 },
	{ .name="getcontext",		.number=SYS_getcontext,	.matchs=0 },
	{ .name="setcontext",		.number=SYS_setcontext,	.matchs=0 },
	{ .name="swapcontext",		.number=SYS_swapcontext,	.matchs=0 },
	{ .name="swapoff",		.number=SYS_swapoff,	.matchs=0 },
	{ .name="__acl_get_link",		.number=SYS___acl_get_link,	.matchs=0 },
	{ .name="__acl_set_link",		.number=SYS___acl_set_link,	.matchs=0 },
	{ .name="__acl_delete_link",		.number=SYS___acl_delete_link,	.matchs=0 },
	{ .name="__acl_aclcheck_link",		.number=SYS___acl_aclcheck_link,	.matchs=0 },
	{ .name="sigwait",		.number=SYS_sigwait,	.matchs=0 },
	{ .name="thr_create",		.number=SYS_thr_create,	.matchs=0 },
	{ .name="thr_exit",		.number=SYS_thr_exit,	.matchs=0 },
	{ .name="thr_self",		.number=SYS_thr_self,	.matchs=0 },
	{ .name="thr_kill",		.number=SYS_thr_kill,	.matchs=0 },
	{ .name="_umtx_lock",		.number=SYS__umtx_lock,	.matchs=0 },
	{ .name="_umtx_unlock",		.number=SYS__umtx_unlock,	.matchs=0 },
	{ .name="jail_attach",		.number=SYS_jail_attach,	.matchs=0 },
	{ .name="extattr_list_fd",		.number=SYS_extattr_list_fd,	.matchs=0 },
	{ .name="extattr_list_file",		.number=SYS_extattr_list_file,	.matchs=0 },
	{ .name="extattr_list_link",		.number=SYS_extattr_list_link,	.matchs=0 },
	{ .name="ksem_timedwait",		.number=SYS_ksem_timedwait,	.matchs=0 },
	{ .name="thr_suspend",		.number=SYS_thr_suspend,	.matchs=0 },
	{ .name="thr_wake",		.number=SYS_thr_wake,	.matchs=0 },
	{ .name="kldunloadf",		.number=SYS_kldunloadf,	.matchs=0 },
	{ .name="audit",		.number=SYS_audit,	.matchs=0 },
	{ .name="auditon",		.number=SYS_auditon,	.matchs=0 },
	{ .name="getauid",		.number=SYS_getauid,	.matchs=0 },
	{ .name="setauid",		.number=SYS_setauid,	.matchs=0 },
	{ .name="getaudit",		.number=SYS_getaudit,	.matchs=0 },
	{ .name="setaudit",		.number=SYS_setaudit,	.matchs=0 },
	{ .name="getaudit_addr",		.number=SYS_getaudit_addr,	.matchs=0 },
	{ .name="setaudit_addr",		.number=SYS_setaudit_addr,	.matchs=0 },
	{ .name="auditctl",		.number=SYS_auditctl,	.matchs=0 },
	{ .name="_umtx_op",		.number=SYS__umtx_op,	.matchs=0 },
	{ .name="thr_new",		.number=SYS_thr_new,	.matchs=0 },
	{ .name="sigqueue",		.number=SYS_sigqueue,	.matchs=0 },
	{ .name="kmq_open",		.number=SYS_kmq_open,	.matchs=0 },
	{ .name="kmq_setattr",		.number=SYS_kmq_setattr,	.matchs=0 },
	{ .name="kmq_timedreceive",		.number=SYS_kmq_timedreceive,	.matchs=0 },
	{ .name="kmq_timedsend",		.number=SYS_kmq_timedsend,	.matchs=0 },
	{ .name="kmq_notify",		.number=SYS_kmq_notify,	.matchs=0 },
	{ .name="kmq_unlink",		.number=SYS_kmq_unlink,	.matchs=0 },
	{ .name="abort2",		.number=SYS_abort2,	.matchs=0 },
	{ .name="thr_set_name",		.number=SYS_thr_set_name,	.matchs=0 },
	{ .name="aio_fsync",		.number=SYS_aio_fsync,	.matchs=0 },
	{ .name="rtprio_thread",		.number=SYS_rtprio_thread,	.matchs=0 },
	{ .name="sctp_peeloff",		.number=SYS_sctp_peeloff,	.matchs=0 },
	{ .name="sctp_generic_sendmsg",		.number=SYS_sctp_generic_sendmsg,	.matchs=0 },
	{ .name="sctp_generic_sendmsg_iov",		.number=SYS_sctp_generic_sendmsg_iov,	.matchs=0 },
	{ .name="sctp_generic_recvmsg",		.number=SYS_sctp_generic_recvmsg,	.matchs=0 },
	{ .name="pread",		.number=SYS_pread,	.matchs=0 },
	{ .name="pwrite",		.number=SYS_pwrite,	.matchs=0 },
	{ .name="mmap",		.number=SYS_mmap,	.matchs=0 },
	{ .name="lseek",		.number=SYS_lseek,	.matchs=0 },
	{ .name="truncate",		.number=SYS_truncate,	.matchs=0 },
	{ .name="ftruncate",		.number=SYS_ftruncate,	.matchs=0 },
	{ .name="thr_kill2",		.number=SYS_thr_kill2,	.matchs=0 },
	{ .name="shm_open",		.number=SYS_shm_open,	.matchs=0 },
	{ .name="shm_unlink",		.number=SYS_shm_unlink,	.matchs=0 },
	{ .name="cpuset",		.number=SYS_cpuset,	.matchs=0 },
	{ .name="cpuset_setid",		.number=SYS_cpuset_setid,	.matchs=0 },
	{ .name="cpuset_getid",		.number=SYS_cpuset_getid,	.matchs=0 },
	{ .name="cpuset_getaffinity",		.number=SYS_cpuset_getaffinity,	.matchs=0 },
	{ .name="cpuset_setaffinity",		.number=SYS_cpuset_setaffinity,	.matchs=0 },
	{ .name="faccessat",		.number=SYS_faccessat,	.matchs=0 },
	{ .name="fchmodat",		.number=SYS_fchmodat,	.matchs=0 },
	{ .name="fchownat",		.number=SYS_fchownat,	.matchs=0 },
	{ .name="fexecve",		.number=SYS_fexecve,	.matchs=0 },
	{ .name="fstatat",		.number=SYS_fstatat,	.matchs=0 },
	{ .name="futimesat",		.number=SYS_futimesat,	.matchs=0 },
	{ .name="linkat",		.number=SYS_linkat,	.matchs=0 },
	{ .name="mkdirat",		.number=SYS_mkdirat,	.matchs=0 },
	{ .name="mkfifoat",		.number=SYS_mkfifoat,	.matchs=0 },
	{ .name="mknodat",		.number=SYS_mknodat,	.matchs=0 },
	{ .name="openat",		.number=SYS_openat,	.matchs=0 },
	{ .name="readlinkat",		.number=SYS_readlinkat,	.matchs=0 },
	{ .name="renameat",		.number=SYS_renameat,	.matchs=0 },
	{ .name="symlinkat",		.number=SYS_symlinkat,	.matchs=0 },
	{ .name="unlinkat",		.number=SYS_unlinkat,	.matchs=0 },
	{ .name="posix_openpt",		.number=SYS_posix_openpt,	.matchs=0 },
	{ .name="gssd_syscall",		.number=SYS_gssd_syscall,	.matchs=0 },
	{ .name="jail_get",		.number=SYS_jail_get,	.matchs=0 },
	{ .name="jail_set",		.number=SYS_jail_set,	.matchs=0 },
	{ .name="jail_remove",		.number=SYS_jail_remove,	.matchs=0 },
	{ .name="closefrom",		.number=SYS_closefrom,	.matchs=0 },
	{ .name="__semctl",		.number=SYS___semctl,	.matchs=0 },
	{ .name="msgctl",		.number=SYS_msgctl,	.matchs=0 },
	{ .name="shmctl",		.number=SYS_shmctl,	.matchs=0 },
	{ .name="lpathconf",		.number=SYS_lpathconf,	.matchs=0 },
	{ .name="pselect",		.number=SYS_pselect,	.matchs=0 },
	{}
};

#endif
